<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="DESKTOP-BCLBHS1" failures="0" tests="0" name="MarketingTestCase-001" time="9.28" errors="0" timestamp="2023-12-07T12:05:03 IST">
  <testcase classname="com.example.tests.BaseTest" name="@AfterClass afterClass" time="0.005">
    <failure type="java.lang.NullPointerException" message="Cannot invoke &amp;quot;com.example.page.common.CommonReusableCodes.close()&amp;quot; because &amp;quot;this.cc&amp;quot; is null">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "com.example.page.common.CommonReusableCodes.close()" because "this.cc" is null
at com.example.tests.BaseTest.afterClass(BaseTest.java:65)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassConfigurations(TestMethodWorker.java:229)
at org.testng.internal.invokers.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:215)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:131)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @AfterClass afterClass -->
  <testcase classname="com.example.testscripts.MarketingAccountTestScripts" name="verifyAccountEditableTC004" time="0.0">
    <ignored/>
  </testcase> <!-- verifyAccountEditableTC004 -->
  <testcase classname="com.example.testscripts.MarketingAccountTestScripts" name="verifyDeleteAccountTC005" time="0.0">
    <ignored/>
  </testcase> <!-- verifyDeleteAccountTC005 -->
  <testcase classname="com.example.testscripts.MarketingAccountTestScripts" name="verifySearchAccountTC002" time="0.0">
    <ignored/>
  </testcase> <!-- verifySearchAccountTC002 -->
  <testcase classname="com.example.testscripts.MarketingAccountTestScripts" name="verifyDuplicateAccountTC003" time="0.0">
    <ignored/>
  </testcase> <!-- verifyDuplicateAccountTC003 -->
</testsuite> <!-- MarketingTestCase-001 -->
